config/routes.rb
Rails.application.routes.draw do
  get 'usages/index'
  get 'trasections/index'
  get 'features/index'
  get 'subscriptions/index'
  get 'buyers/index'
  get 'plans/index'
  get 'users/index'
  devise_for :users


  
  root "home#index"
  # resources :users
  # resources :plans
  resources :users do
    resources :plans do
      resources :features
    end

    resources :subscriptions do 
      resources :usages  
      resources :trasections
    end
    
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < User
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < User
	has_many :subscriptions, foreign_key: :user_id, dependent: :delete_all
	has_many :plans, through: :subscriptions

end

app/models/feature.rb
class Feature < ApplicationRecord
	acts_as_paranoid
	belongs_to :plan, optional: true
	has_many :trasections
	has_many :usages, foreign_key: :feature_id

	has_many :trasections, foreign_key: :feature_id
end

app/models/plan.rb
class Plan < ApplicationRecord
	acts_as_paranoid
	has_many :subscriptions, foreign_key: :plan_id, dependent: :destroy
	has_many :buyers, through: :subscriptions, foreign_key: :plan_id
	has_many :features,foreign_key: :plan_id, dependent: :destroy
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  acts_as_paranoid
  belongs_to :buyer, class_name: "User", foreign_key: "user_id", optional: true
  belongs_to :plan, optional: true
  has_many :usages, foreign_key: :subscription_id, dependent: :nullify
  has_many :trasections, foreign_key: :subscription_id, dependent: :nullify

end

app/models/trasection.rb
class Trasection < ApplicationRecord
	belongs_to :subscription, optional: true
	belongs_to :feature, optional: true

end

app/models/usage.rb
class Usage < ApplicationRecord
	belongs_to :subscription, optional: true
	belongs_to :feature, optional: true	

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :user_send

  def user_send
    UserMailer.user_send(self).deliver_later
  end
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!
  def index
    # byebug
    @plans=Plan.all
  end

  def new
    @plan = Plan.new
    begin
      authorize @plan
    rescue
      render :file => "#{Rails.root}/public/404.html",  layout: false, status: :not_found
    end
  end

  def create
    @plan = Plan.new(plan_params)
    
    # byebug
    # @plan.id = Integer(plan_params[:id])
    authorize @plan

    if @plan.save

      redirect_to user_plan_path(params[:user_id], @plan.id)
    else
      redirect_to users_path
    end
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def edit
    @plan=Plan.find(params[:id])
  end

  def update
    @plan=Plan.find(params[:id])
    if @plan.update(plan_params)
      redirect_to user_plans_path(current_user.id)
    else
      render 'edit'
    end
  end

  

  def destroy
    @plan = Plan.find(params[:id])
    authorize @plan
    @plan.destroy
    redirect_to user_plans_path(current_user.id)
    
  end

  private 

  def plan_params
    params.require(:plan).permit(:name, :fee)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
  end

  def show
    @user = User.find(params[:id])
  end


  def destroy
    # @plan = Plan.find(params[:plan_id])
    # @plan.destroy
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/trasections_helper.rb
module TrasectionsHelper
end

app/helpers/usages_helper.rb
module UsagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%=link_to 'Test Project', root_path, class: "navbar-brand"%>
    <!-- <a class="navbar-brand" href="#">Book Mania</a> -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

<!-- Here we can add links to every page we want to go, ofcourse not models index,show etc page -->

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
  
        <%if !user_signed_in? %>

          <li class="nav-item">
            <%=link_to 'Sign in', new_user_session_path, class: 'nav-link'%>
          </li>

          <li class="nav-item">
            <%=link_to 'Sign up', new_user_registration_path, class: 'nav-link'%>
          </li>

        <%else%>

          <li class="nav-item">
            <%=link_to 'All Plans', user_plans_path(current_user), class: 'nav-link'%>
          </li>

          <li class="nav-item">
            <%=link_to 'Edit User', edit_user_registration_path, class: 'nav-link'%>
          </li>


          <%if current_user.type=="Buyer"%>
            <li class="nav-item">
             <%=link_to 'Subscriptions', user_subscriptions_path(current_user.id), class: 'nav-link'%>
            </li>
          <%else%>
            <li class="nav-item">
              <%=link_to 'Create Plan', new_user_plan_path(current_user.id), class: 'nav-link'%>
            </li>

          <%end%>

          <li class="nav-item">
            <%=link_to 'Back', :back, class: 'nav-link'%>
          </li>

          

         
        <%end%>

        

        
      </ul>
      <%if user_signed_in? %>

        <form class="d-flex">
          <%=link_to 'Sign out', destroy_user_session_path, class: 'nav-link', method: :delete%>
        </form>
      <%end%>
    </div>

    <!-- Upto here is our nav bar -->
  
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home Index Page</h1>