config/routes.rb
Rails.application.routes.draw do
  get 'usages/index'
  get 'trasections/index'
  get 'features/index'
  get 'subscriptions/index'
  get 'buyers/index'
  get 'plans/index'
  get 'users/index'
  devise_for :users


  
  root "home#index"
  # resources :users
  # resources :plans
  resources :users do
    resources :plans do
      resources :features
    end

    resources :subscriptions do 
      resources :usages  
      resources :trasections
    end
    
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < User
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < User
	has_many :subscriptions, foreign_key: :user_id, dependent: :delete_all
	has_many :plans, through: :subscriptions

end

app/models/feature.rb
class Feature < ApplicationRecord
	acts_as_paranoid
	belongs_to :plan, optional: true
	has_many :trasections
	has_many :usages, foreign_key: :feature_id

	has_many :trasections, foreign_key: :feature_id
end

app/models/plan.rb
class Plan < ApplicationRecord
	acts_as_paranoid
	has_many :subscriptions, foreign_key: :plan_id, dependent: :destroy
	has_many :buyers, through: :subscriptions, foreign_key: :plan_id
	has_many :features,foreign_key: :plan_id, dependent: :destroy
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  acts_as_paranoid
  belongs_to :buyer, class_name: "User", foreign_key: "user_id", optional: true
  belongs_to :plan, optional: true
  has_many :usages, foreign_key: :subscription_id, dependent: :nullify
  has_many :trasections, foreign_key: :subscription_id, dependent: :nullify

end

app/models/trasection.rb
class Trasection < ApplicationRecord
	belongs_to :subscription, optional: true
	belongs_to :feature, optional: true

end

app/models/usage.rb
class Usage < ApplicationRecord
	belongs_to :subscription, optional: true
	belongs_to :feature, optional: true	

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :user_send

  def user_send
    UserMailer.user_send(self).deliver_later
  end
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!
  def index
    # byebug
    @plans=Plan.all
  end

  def new
    @plan = Plan.new
    begin
      authorize @plan
    rescue
      render :file => "#{Rails.root}/public/404.html",  layout: false, status: :not_found
    end
  end

  def create
    @plan = Plan.new(plan_params)
    
    # byebug
    # @plan.id = Integer(plan_params[:id])
    authorize @plan

    if @plan.save

      redirect_to user_plan_path(params[:user_id], @plan.id)
    else
      redirect_to users_path
    end
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def edit
    @plan=Plan.find(params[:id])
  end

  def update
    @plan=Plan.find(params[:id])
    if @plan.update(plan_params)
      redirect_to user_plans_path(current_user.id)
    else
      render 'edit'
    end
  end

  

  def destroy
    @plan = Plan.find(params[:id])
    authorize @plan
    @plan.destroy
    redirect_to user_plans_path(current_user.id)
    
  end

  private 

  def plan_params
    params.require(:plan).permit(:name, :fee)
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def index
    @subscriptions = Subscription.all
    # authorize @subscriptions
  end

  def new

    @subscription = Subscription.new

  end

  def create
    @subscription = Subscription.new(sub_params)

    if @subscription.save
      redirect_to new_user_subscription_trasection_path(params[:user_id], @subscription.id)
    else
      redirect_to users_path
      
    end
    
  end

  def edit
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    
    @subscription.destroy
    redirect_to user_subscriptions_path(current_user.id)
  end

  private

  def sub_params
    params.require(:subscription).permit(:plan_id, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
  end

  def show
    @user = User.find(params[:id])
  end


  def destroy
    # @plan = Plan.find(params[:plan_id])
    # @plan.destroy
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/trasections_helper.rb
module TrasectionsHelper
end

app/helpers/usages_helper.rb
module UsagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subscriptions/create.html.erb
<h1>Subscription Create Page</h1>

app/views/subscriptions/destroy.html.erb
<h1>Subscription Destroy Page</h1>

app/views/subscriptions/index.html.erb
<%if policy(@subscriptions).index?%>
	<h1>Subscriptions Index Page</h1>
	
	<table class="table table-striped table-bordered table-hover">
	  <thead class="table-dark">
	    <tr>
	      <th>Plan Name</th>
	      <th>Plan Fee</th>
	      <th>Show Transections</th>
	      <th>Remove Subscription</th>
	      <th>Pay Bill</th>


	      <!-- <th colspan="3"></th> -->
	    </tr>
	  </thead>


	  <tbody>
	    
		
	<%@subscriptions.each do |s|%>
		<%if s.user_id==current_user.id%>
			<tr>
				<td><%=s.plan.name%></td>
				<td><%=s.plan.fee%></td>
				<td><%=link_to "Transections", user_subscription_trasections_path(current_user.id,s.id)%></td>
				<td><%=link_to "Remove Subscription", user_subscription_path(current_user.id,s), method: :delete, data: {confirm: "Are you sure?"}%></td>
				<td><%=link_to "Pay Bill", new_user_subscription_trasection_path(current_user.id,s.id)%></td>
				
				<%end%>
			</tr>
		<%end%>

			
	  </tbody>
	</table>
<%elsif !policy(@subscriptions).index? %>
	<h1>Subscriptions Index Page</h1>
	

	<table class="table table-striped table-bordered table-hover">
	  <thead class="table-dark">
	    <tr>
	      <th>User Name</th>
	      <th>Plan Name</th>
	      <th>Plan Fee</th>
	      <th>Create Usage</th>
	      <th>Remove Subscription</th>
	      


	      <!-- <th colspan="3"></th> -->
	    </tr>
	  </thead>


	  <tbody>
	    
		
	<%@subscriptions.each do |s|%>
		<%if params[:plan_id] != nil &&  Integer(params[:plan_id])==s.plan_id%>
		<tr>
			<td><%=s.buyer.name%></td>
			<td><%=s.plan.name%></td>
			<td><%=s.plan.fee%></td>
			<td><%=link_to "Create", new_user_subscription_usage_path(params[:user_id],s.id)%></td>
			<td><%=link_to "Remove Subscription", user_subscription_path(current_user.id,s), method: :delete, data: {confirm: "Are you sure?"}%></td>

		</tr>
		<%end%>
						
	<%end%>

			
	  </tbody>
	</table>
<%else%>
	<%render :file => "#{Rails.root}/public/404.html",  layout: false, status: :not_found%>
<%end%>


	

app/views/subscriptions/new.html.erb
<h1>Subscription New Page</h1>


<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Fee</th>
      <th>Subscribe</th>


      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>


  <tbody>
    
		
	<%=form_for @subscription, url: {action: "create"} do |subs|%>
		<%if params[:plan_id] != nil%>
			<td><%=Plan.find(params[:plan_id]).name%></td>
			<td><%=Plan.find(params[:plan_id]).fee%></td>
		<%else%>
			<td>nil</td>
			<td>nil</td>
		<%end%>
		
		<%=subs.hidden_field :user_id, value: params[:user_id]%>
		<%=subs.hidden_field :plan_id, value: params[:plan_id]%>

		<td><%=subs.submit%></td>
		
	<%end%>
		
  </tbody>
</table>

app/views/subscriptions/show.html.erb
<h1>Subscription Show Page</h1>