config/routes.rb
Rails.application.routes.draw do
  get 'usages/index'
  get 'trasections/index'
  get 'features/index'
  get 'subscriptions/index'
  get 'buyers/index'
  get 'plans/index'
  get 'users/index'
  devise_for :users


  
  root "home#index"
  # resources :users
  # resources :plans
  resources :users do
    resources :plans do
      resources :features
    end

    resources :subscriptions do 
      resources :usages  
      resources :trasections
    end
    
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < User
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < User
	has_many :subscriptions, foreign_key: :user_id, dependent: :delete_all
	has_many :plans, through: :subscriptions

end

app/models/feature.rb
class Feature < ApplicationRecord
	acts_as_paranoid
	belongs_to :plan, optional: true
	has_many :trasections
	has_many :usages, foreign_key: :feature_id

	has_many :trasections, foreign_key: :feature_id
end

app/models/plan.rb
class Plan < ApplicationRecord
	acts_as_paranoid
	has_many :subscriptions, foreign_key: :plan_id, dependent: :destroy
	has_many :buyers, through: :subscriptions, foreign_key: :plan_id
	has_many :features,foreign_key: :plan_id, dependent: :destroy
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  acts_as_paranoid
  belongs_to :buyer, class_name: "User", foreign_key: "user_id", optional: true
  belongs_to :plan, optional: true
  has_many :usages, foreign_key: :subscription_id, dependent: :nullify
  has_many :trasections, foreign_key: :subscription_id, dependent: :nullify

end

app/models/trasection.rb
class Trasection < ApplicationRecord
	belongs_to :subscription, optional: true
	belongs_to :feature, optional: true

end

app/models/usage.rb
class Usage < ApplicationRecord
	belongs_to :subscription, optional: true
	belongs_to :feature, optional: true	

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :user_send

  def user_send
    UserMailer.user_send(self).deliver_later
  end
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!
  def index
    # byebug
    @plans=Plan.all
  end

  def new
    @plan = Plan.new
    begin
      authorize @plan
    rescue
      render :file => "#{Rails.root}/public/404.html",  layout: false, status: :not_found
    end
  end

  def create
    @plan = Plan.new(plan_params)
    
    # byebug
    # @plan.id = Integer(plan_params[:id])
    authorize @plan

    if @plan.save

      redirect_to user_plan_path(params[:user_id], @plan.id)
    else
      redirect_to users_path
    end
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def edit
    @plan=Plan.find(params[:id])
  end

  def update
    @plan=Plan.find(params[:id])
    if @plan.update(plan_params)
      redirect_to user_plans_path(current_user.id)
    else
      render 'edit'
    end
  end

  

  def destroy
    @plan = Plan.find(params[:id])
    authorize @plan
    @plan.destroy
    redirect_to user_plans_path(current_user.id)
    
  end

  private 

  def plan_params
    params.require(:plan).permit(:name, :fee)
  end

end

app/controllers/usages_controller.rb
class UsagesController < ApplicationController
  def index
  end

  def new
    @usage = Usage.new
  end

  def create
    @usage = Usage.new(usage_params)
    if @usage.save
      redirect_to user_subscriptions_path(params[:user_id],:plan_id=>Subscription.find(Integer(params[:subscription_id])).plan.id)
    else 
      redirect_to user_plans_path(Subscription.find(Integer(params[:subscription_id])).buyer.id)
    end
  end

  def edit
    @usage=Usage.find(params[:id])
  end

  def update
    @usage=Usage.find(params[:id])
    if @usage.update(usage_params)
      redirect_to user_plans_path(current_user.id)
    else
      render root_path
    end
  end

  private

  def usage_params
    params.require(:usage).permit(:subscription_id, :feature_id, :total_usage, :usage_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
  end

  def show
    @user = User.find(params[:id])
  end


  def destroy
    # @plan = Plan.find(params[:plan_id])
    # @plan.destroy
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/trasections_helper.rb
module TrasectionsHelper
end

app/helpers/usages_helper.rb
module UsagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buyers/index.html.erb
<h1>Buyers#index</h1>
<p>Find me in app/views/buyers/index.html.erb</p>

app/views/plans/create.html.erb
<h1>Plan Create Page</h1>

app/views/plans/destroy.html.erb
<h1>Plan Destroy Page</h1>

Plan Has Succefully destroyed

app/views/plans/edit.html.erb
<h1>Plan Edit Page</h1>

<%= form_for @plan, url: {action: "update"} do |plan| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
        <% @plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field form-group">
    <%= plan.text_field :name,
      class: "form-control", placeholder: "Plan Name"
    %>
  </div>
  <br>
  <div class="field form-group">
    <%= plan.text_field :fee,
      class: "form-control", placeholder: "Price"
     %>
  </div>
  <br>
  <div class="actions">
    <%= plan.submit %>
  </div>
<% end %>

app/views/plans/index.html.erb
<h1>Plans index Page</h1>


	<table class="table table-striped table-bordered table-hover">
	  <thead class="table-dark">
	    <tr>
	      <th>Name</th>
	      <th>Fee</th>
	      <th>Show Features</th>
	      <%if current_user.type == "Admin"%>
	      	<th>Delete Plan</th>
	      	<th>Show Plan Subscriptions</th>
	      	<th>Edit Plan</th>
	      <%else%>
	      	<th>Subscribe Plan</th>
	      <%end%>

	      <!-- <th colspan="3"></th> -->
	    </tr>
	  </thead>


	  <tbody>
	    
			<%@plans.each do |plan|%>
			<tr>
				<td><%=plan.name%></td>
				<td><%=plan.fee%></td>
				<td><%=link_to "Show Features", user_plan_path(current_user.id,plan.id)%></td>

				<%if policy(plan).index?%>
					<td><%=link_to "Delete",user_plan_path(current_user.id, plan.id), method: :delete, data: {confirm: "Are you sure?"}%></td>
					<td><%=link_to "Subscriptions", user_subscriptions_path(current_user.id, :plan_id=>plan.id)%></td>
					<td><%=link_to "Edit", edit_user_plan_path(current_user.id, plan.id)%></td>
				<%else%>
					
					<td><%=link_to "Subscribe",new_user_subscription_path(current_user.id, :plan_id=>plan.id)%></td>
					
				<%end%>
			</tr>
			<%end%>
			

	  
	  </tbody>
	</table>




	

app/views/plans/new.html.erb
<h1>Plan New Page</h1>


<%= form_for @plan, url: {action: "create"} do |plan| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
        <% @plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field form-group">
    <%= plan.text_field :name,
      class: "form-control", placeholder: "Plan Name"
    %>
  </div>
  <br>
  <div class="field form-group">
    <%= plan.text_field :fee,
      class: "form-control", placeholder: "Price"
     %>
  </div>
  <br>
  <div class="actions">
    <%= plan.submit %>
  </div>
<% end %>

app/views/plans/show.html.erb
<h1>Plan Show Page														
	<%if current_user.type=="Admin"%>
		<%=link_to "Create Feature", new_user_plan_feature_path(current_user.id,params[:id]), class: "btn btn-secondary "%>
	<%end%>
</h1>


<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Feature Limit</th>
      <th>Feature Price</th>
      <%if current_user.type=="Admin"%>
      	<th>Edit Feature</th>
      <%end%>

      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>


  <tbody>
    
		
	<%@plan.features.each do |pf|%>
	<tr>
		<td><%=pf.name%></td>
		<td><%=pf.code%></td>
		<td><%=pf.limit%></td>
		<td><%=pf.price%></td>
		<%if current_user.type=="Admin"%>
      	<td><%=link_to "Edit Feature", edit_user_plan_feature_path(current_user.id,params[:id],pf.id)%></td>
    <%end%>
		
	</tr>
	<%end%>
		

  
  </tbody>
</table>

app/views/plans/update.html.erb
<h1>Plan Update Page</h1>

app/views/usages/edit.html.erb
<h1>Usage Edit Page</h1>


<%= form_for @usage, url: {action: "update"} do |usage| %>
  <% if @usage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usage.errors.count, "error") %> prohibited this usage from being saved:</h2>

      <ul>
        <% @usage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field form-group">
    <%= usage.text_field :feature_id,
      class: "form-control", placeholder: "Feature id"
    %>
    <br>
  </div>
  <%=link_to "All Features", user_plan_features_path(params[:user_id],Subscription.find(Integer(params[:subscription_id])).plan.id)%>
  <br>
  <%=usage.hidden_field :subscription_id, value: params[:subscription_id]%>
  <br>
  <div class="field form-group">
    <%= usage.text_field :total_usage,
      class: "form-control", placeholder: "Over Useage"
     %>
  </div>
  <br>
  <div class="field form-group">
    <%= usage.date_field :usage_date,
      class: "form-control", placeholder: "Useage date"
     %>
  </div>
  <br>
  <div class="actions">
    <%= usage.submit %>
  </div>
<% end %>

app/views/usages/index.html.erb
<h1>Usages Index Page</h1>

app/views/usages/new.html.erb
<h1>Usage New Page</h1>


<%= form_for @usage, url: {action: "create"} do |usage| %>

  <% if @usage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usage.errors.count, "error") %> prohibited this usage from being saved:</h2>

      <ul>
        <% @usage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field form-group">
    <%= usage.text_field :feature_id,
      class: "form-control", placeholder: "Feature id"
    %>
    <br>
  </div>

  <%if Subscription.find(Integer(params[:subscription_id])).plan != nil%>
    <%=link_to "All Features", user_plan_features_path(params[:user_id],Subscription.find(Integer(params[:subscription_id])).plan.id)%>
  <%else%>
    All Features
  <%end%>
  
  <br>
  <%=usage.hidden_field :subscription_id, value: params[:subscription_id]%>
  <br>
  <div class="field form-group">
    <%= usage.text_field :total_usage,
      class: "form-control", placeholder: "Over Useage"
     %>
  </div>
  <br>
  <div class="field form-group">
    <%= usage.date_field :usage_date,
      class: "form-control", placeholder: "Useage date"
     %>
  </div>
  <br>
  <div class="actions">
    <%= usage.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users Index Page</h1>

app/views/users/show.html.erb
<%if user_signed_in?%>
	<h1>User Show Page</h1>

	<table class="table table-striped table-bordered table-hover">
	  <thead class="table-dark">
	    <tr>
	      <th>Name</th>
	      <th>Fee</th>
	      <!-- <th colspan="3"></th> -->
	    </tr>
	  </thead>


	  <tbody>
	    
			<%@user.plans.each do |p| %>
			<tr>
				<td><%=p.name%></td>
				<td><%=p.fee%></td>
				
				
			</tr>
			<%end%>

	  
	  </tbody>
	</table>
<%end%>