config/routes.rb
Rails.application.routes.draw do
  get 'usages/index'
  get 'trasections/index'
  get 'features/index'
  get 'subscriptions/index'
  get 'buyers/index'
  get 'plans/index'
  get 'users/index'
  devise_for :users


  
  root "home#index"
  # resources :users
  # resources :plans
  resources :users do
    resources :plans do
      resources :features
    end

    resources :subscriptions do 
      resources :usages  
      resources :trasections
    end
    
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < User
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < User
	has_many :subscriptions, foreign_key: :user_id, dependent: :delete_all
	has_many :plans, through: :subscriptions

end

app/models/feature.rb
class Feature < ApplicationRecord
	acts_as_paranoid
	belongs_to :plan, optional: true
	has_many :trasections
	has_many :usages, foreign_key: :feature_id

	has_many :trasections, foreign_key: :feature_id
end

app/models/plan.rb
class Plan < ApplicationRecord
	acts_as_paranoid
	has_many :subscriptions, foreign_key: :plan_id, dependent: :destroy
	has_many :buyers, through: :subscriptions, foreign_key: :plan_id
	has_many :features,foreign_key: :plan_id, dependent: :destroy
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  acts_as_paranoid
  belongs_to :buyer, class_name: "User", foreign_key: "user_id", optional: true
  belongs_to :plan, optional: true
  has_many :usages, foreign_key: :subscription_id, dependent: :nullify
  has_many :trasections, foreign_key: :subscription_id, dependent: :nullify

end

app/models/trasection.rb
class Trasection < ApplicationRecord
	belongs_to :subscription, optional: true
	belongs_to :feature, optional: true

end

app/models/usage.rb
class Usage < ApplicationRecord
	belongs_to :subscription, optional: true
	belongs_to :feature, optional: true	

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :user_send

  def user_send
    UserMailer.user_send(self).deliver_later
  end
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  def index
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  def index
    @features = Feature.all
  end

  def new
    @feature = Feature.new
  end

  def create
    @plan = params[:plan_id]
    @feature = Feature.new(feature_params)
    @feature.plan_id=@plan
    # byebug
    if @feature.save
      redirect_to user_plans_path(current_user.id)

    else
      redirect_to users_path
    end

  end

  def edit
    @feature=Feature.find(params[:id])
  end

  def update
    @feature=Feature.find(params[:id])
    if @feature.update(feature_params)
      redirect_to user_plans_path(current_user.id)
    else
      render root_path
    end
  end

  # def destroy

  #   @feature = Feature.find(params[:id])
  #   @feature.destroy
  #   redirect_to user_plans_path(current_user.id)
    
  # end

  private

  def feature_params
    params.require(:feature).permit(:name,:code, :price, :limit, :plan_id)
  end
    

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!
  def index
    # byebug
    @plans=Plan.all
  end

  def new
    @plan = Plan.new
    begin
      authorize @plan
    rescue
      render :file => "#{Rails.root}/public/404.html",  layout: false, status: :not_found
    end
  end

  def create
    @plan = Plan.new(plan_params)
    
    # byebug
    # @plan.id = Integer(plan_params[:id])
    authorize @plan

    if @plan.save

      redirect_to user_plan_path(params[:user_id], @plan.id)
    else
      redirect_to users_path
    end
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def edit
    @plan=Plan.find(params[:id])
  end

  def update
    @plan=Plan.find(params[:id])
    if @plan.update(plan_params)
      redirect_to user_plans_path(current_user.id)
    else
      render 'edit'
    end
  end

  

  def destroy
    @plan = Plan.find(params[:id])
    authorize @plan
    @plan.destroy
    redirect_to user_plans_path(current_user.id)
    
  end

  private 

  def plan_params
    params.require(:plan).permit(:name, :fee)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
  end

  def show
    @user = User.find(params[:id])
  end


  def destroy
    # @plan = Plan.find(params[:plan_id])
    # @plan.destroy
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/trasections_helper.rb
module TrasectionsHelper
end

app/helpers/usages_helper.rb
module UsagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/features/edit.html.erb
<h1>Features Edit Page</h1>
<%=form_for @feature, url: {action: "update"} do |f|%>
	<div class="field form-group">
	    <%= f.text_field :name, class: "form-control", placeholder: "Feature Name"%>
  	</div></br>
  	<div class="field form-group">
	    <%= f.text_field :code, class: "form-control", placeholder: "Feature Code"%>
  	</div></br>
  	<div class="field form-group">
	    <%= f.text_field :price, class: "form-control", placeholder: "Feature Price Per Unit"%>
  	</div></br>
  	<div class="field form-group">
	    <%= f.text_field :limit, class: "form-control", placeholder: "Feature Units Limit"%>
  	</div></br>

	<%=f.submit%>
<%end%>

app/views/features/index.html.erb
<h1>Features Index Page</h1>


<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Feature Name</th>
      <th>Feature id</th>
      <th>Plan Name</th>
      <th>Show Feature</th>

      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>


  <tbody>
    
		
	<%@features.each do |fea| %>
	<%if fea.plan_id != nil && fea.plan_id == Integer(params[:plan_id])%>
		<tr>
			<td><%=fea.name%></td>
			<td><%=fea.id%></td>
			<td><%=fea.plan.name%></td>
			<td><%=link_to "Show Feature", user_plan_feature_path(params[:user_id],fea.plan_id,fea.id)%></td>
	</tr>
	<%end%>
	<%end%>
		

  
  </tbody>
</table>

app/views/features/new.html.erb
<h1>Features New Page</h1>
<%=form_for @feature, url: {action: "create"} do |f|%>
	<div class="field form-group">
	    <%= f.text_field :name, class: "form-control", placeholder: "Feature Name"%>
  	</div></br>
  	<div class="field form-group">
	    <%= f.text_field :code, class: "form-control", placeholder: "Feature Code"%>
  	</div></br>
  	<div class="field form-group">
	    <%= f.text_field :price, class: "form-control", placeholder: "Feature Price Per Unit"%>
  	</div></br>
  	<div class="field form-group">
	    <%= f.text_field :limit, class: "form-control", placeholder: "Feature Units Limit"%>
  	</div></br>

	<%=f.submit%>
<%end%>

app/views/features/show.html.erb
<h1>Feature Show Page</h1>